MovieRental/Areas/Admin/Controllers/BulkLoadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using MovieRental.Externals;
using MovieRental.Models;
using MovieRental.Data;

namespace MovieRental.Areas.Admin.Controllers
{
    public class BulkLoadController : Controller
    {
        //
        // GET: /Admin/BulkLoad/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string movieList, double defaultRentalRate, int defaultQty)
        {
            string[] titles = Regex.Split(movieList, "\r\n|\r|\n");
            List<string> unresolvedTitles = new List<string>();
            List<Movie> resolvedMovie = new List<Movie>();
            foreach (string title in titles)
            {
                Movie m = OMDBService.GetMoviesByTitle(title);
                if (m != null)
                {
                    m.RentalRate = defaultRentalRate;
                    m.NoInStock = defaultQty;
                    resolvedMovie.Add(m);
                }
                else
                {
                    if (!string.IsNullOrEmpty(title))
                        unresolvedTitles.Add(title);
                }

            }

            BulkLoadOutput blo = new BulkLoadOutput(unresolvedTitles, resolvedMovie);
            TempData["blo"] = blo;

            return View("BulkOutput", blo);
        }

        [HttpPost]
        public ActionResult Save(string save)
        {
            List<string> messages = new List<string>();
            if (save == "Yes")
            {
                BulkLoadOutput blo = (BulkLoadOutput)TempData["blo"];
                List<Movie> movies = blo == null ? new List<Movie>() : blo.ResolvedMovie;
                MovieRepository rep = new MovieRepository();
                foreach (Movie m in movies)
                {
                    try
                    {
                        rep.Add(m);
                        rep.Save();
                        messages.Add("Successfully add movie " + m.Title);
                    }
                    catch
                    {
                        messages.Add("Unable to add movie " + m.Title + ". Perhaps it is already in the database.");
                    }
                }
            }
            else
            {
                messages.Add("Bulk Load operation is successfully cancelled.");
            }
            return View(messages);
        }

    }
    public class BulkLoadOutput
    {
        public BulkLoadOutput(List<string> unresolvedTitles, List<Movie> resolvedMovie)
        {
            UnresolvedTitles = unresolvedTitles;
            ResolvedMovie = resolvedMovie;
        }
        public List<string> UnresolvedTitles { get; set; }
        public List<Movie> ResolvedMovie { get; set; }
    }
}

MovieRental/Areas/Admin/Views/BulkLoad/BulkOutput.cshtml
@model MovieRental.Areas.Admin.Controllers.BulkLoadOutput
@using MovieRental.Models
@{
    ViewBag.Title = "BulkOutput";
}

<h2>Information Retrieved from Open Movie Database</h2>
@if (Model.UnresolvedTitles.Count > 0)
{
    <h3>Unable to find a match for the following:</h3>
    foreach (string item in Model.UnresolvedTitles)
    {
    <li>@item</li>
    }
}
<div>
    <h3>Match found for the following movies</h3>
    @foreach (var m in Model.ResolvedMovie)
    {
        <div style="width:320px; height:520px;float:left">
            @Html.DisplayFor(modelItem =>m)
        </div>
    }
</div>
<div style="float: left">
    <p>
        Do you want to add all these movies?
    </p>
    <p>
        @using (Html.BeginForm("Save", "BulkLoad"))
        {
            <input style="color: Green; font-weight: bold" type="submit" name="Save" value="Yes" />
            <input style="color: Red; font-weight: bold" type="submit" name="Save" value="No" />
        }
    </p>
</div>

MovieRental/Areas/Admin/Views/BulkLoad/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Movie Bulk Loader</h2>
Enter list of movies (one line per movie) to load
@using (Html.BeginForm())
{
    @Html.TextArea("movieList")
    <p>Default Rental Rate:<br />@Html.TextBox("defaultRentalRate")</p>
    <p>Default Quantity: <br />@Html.TextBox("defaultQty")</p>
    
    <p>
        <input type="submit" value="Submit" />
    </p>
}

MovieRental/Areas/Admin/Views/BulkLoad/Save.cshtml
@{
    ViewBag.Title = "Bulk Load Result";
}

<h2>Bulk Load Result</h2>
@foreach (string message in Model)
{
    <p>
        @message</p>
}